[project]
name = "mcp-server"
version = "0.1.0"
description = "Graphiti MCP Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=2.0.0",
    "openai>=1.68.2",
    "graphiti-core>=0.8.2",
    "azure-identity>=1.21.0",
    "fastapi>=0.110.0",
]
